---
title: "day1-tasks"
author: "Jaslyn Miura"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(janitor)
library(skimr)
```

```{r}

stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv"))

stl_lead <- clean_names(stl_lead)

skimr::skim(stl_lead)

```

```{r}

# prop_white <- ((stl_lead$white)/(stl_lead$total_pop)) * 100

stl_lead_prop <- stl_lead %>%
  mutate(prop_white = (stl_lead$white/stl_lead$total_pop)*100) 
  

```

```{r}

stl_lead_plot <- ggplot(data = stl_lead_prop,
       aes(x = pct_elevated, y = prop_white)) +
  geom_point(alpha = 0.5, color = "purple3")

stl_lead_plot

ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)

```
There appears to be a decreasing trend in the data. Where as pct_elevated increases, the proportion of white population decreases.

```{r}

stl_pct_hist <- ggplot(data = stl_lead_prop, 
       aes(x = pct_elevated)) + 
  geom_histogram(color = "gold", fill = "purple4", size = 2)

stl_pct_hist

ggsave(here::here("figs", "stl_pct_hist.jpg"), height = 5, width = 6)

```

